# -*- coding: utf-8 -*-
"""Credit Risk Decision Simulator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TjMEdAVSheuHgb9yDI-MVArn_wQ5ADeQ
"""

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import joblib
# 
# st.set_page_config(page_title="Credit Risk Simulator", layout="wide")
# 
# # ==============================
# # LOAD FILES
# # ==============================
# @st.cache_resource
# def load_model():
#     return joblib.load("/content/credit_model.pkl")
# 
# @st.cache_data
# def load_base():
#     return pd.read_csv("/content/base_input.csv")
# 
# model = load_model()
# base_input = load_base()
# 
# # ==============================
# # TITLE
# # ==============================
# st.title("💳 Credit Risk & Profitability Simulator")
# 
# st.markdown("""
# Make lending decisions based on **profit**, not just risk.
# This shows how **LGD (business)** can outweigh **model performance (PD)**.
# """)
# 
# # ==============================
# # SIDEBAR INPUT
# # ==============================
# st.sidebar.header("🧾 Borrower Input")
# 
# loan_amount = st.sidebar.number_input("Loan Amount",value=1000)
# interest_rate = st.sidebar.slider("Interest Rate (%)", 5.0, 30.0, 12.0)
# term = st.sidebar.selectbox("Loan Term", [36, 60])
# 
# emp_length_ui = st.sidebar.selectbox( "Employment Length", [ "< 1 year", "1 year", "2 years", "3 years", "4 years", "5 years", "6 years", "7 years", "8 years", "9 years", "10+ years", "Unknown" ])
# home_ownership = st.sidebar.selectbox("Home Ownership", ['RENT', 'OWN', 'MORTGAGE', 'OTHER', 'NONE', 'ANY'])
# dti = st.sidebar.number_input("Debt-to-Income Ratio", value=1.0)
# # -------------------------
# # MAPPING
# # -------------------------
# emp_map = { "< 1 year": 0, "1 year": 1, "2 years": 2, "3 years": 3, "4 years": 4, "5 years": 5, "6 years": 6, "7 years": 7, "8 years": 8, "9 years": 9, "10+ years": 10, "Unknown": -1 }
# emp_length = emp_map[emp_length_ui]
# 
# lgd = st.sidebar.slider("LGD (Loss Given Default)", 0.1, 1.0, 0.9)
# 
# # ==============================
# # PREPARE INPUT
# # ==============================
# input_df = base_input.copy()
# 
# input_df['loan_amnt'] = loan_amount
# input_df['int_rate'] = interest_rate
# input_df['term'] = f"{term} months"
# 
# # ==============================
# # PREDICT PD
# # ==============================
# try:
#     pd_proba = model.predict_proba(input_df)[0, 1]
# except Exception as e:
#     st.error(f"Model error: {e}")
#     st.stop()
# 
# # ==============================
# # ECONOMICS
# # ==============================
# EAD = loan_amount
# interest_income = loan_amount * (interest_rate / 100)
# 
# expected_loss = pd_proba * lgd * EAD
# expected_profit = (1 - pd_proba) * interest_income - expected_loss
# 
# decision = "APPROVE ✅" if expected_profit > 0 else "REJECT ❌"
# 
# # ==============================
# # DISPLAY
# # ==============================
# st.markdown("## 📊 Decision Summary")
# 
# col1, col2, col3 = st.columns(3)
# col1.metric("PD", f"{pd_proba:.2%}")
# col2.metric("Expected Loss", f"${expected_loss:,.0f}")
# col3.metric("Expected Profit", f"${expected_profit:,.0f}")
# 
# st.markdown("---")
# 
# if expected_profit > 0:
#     st.success(f"### {decision}")
# else:
#     st.error(f"### {decision}")
# 
# # ==============================
# # INSIGHT
# # ==============================
# st.markdown("## 🧠 Insight")
# 
# if expected_profit < 0:
#     if pd_proba < 0.3:
#         st.warning("Low risk, but high LGD makes this unprofitable")
#     else:
#         st.warning("High risk + high LGD = loss")
# else:
#     st.success("Profitable under current assumptions")
# 
# # ==============================
# # LGD SENSITIVITY (FIXED)
# # ==============================
# st.markdown("## 🔍 LGD Sensitivity")
# 
# lgd_range = np.linspace(0.1, 1.0, 50)
# 
# profits = [
#     (1 - pd_proba) * interest_income - (pd_proba * l * EAD)
#     for l in lgd_range
# ]
# 
# chart_df = pd.DataFrame({
#     "LGD": lgd_range,
#     "Profit": profits
# })
# 
# st.line_chart(chart_df.set_index("LGD"))
# 
# # ==============================
# # BREAK EVEN
# # ==============================
# st.markdown("## 🎯 Break-even LGD")
# 
# break_even = None
# 
# for l in lgd_range:
#     profit = (1 - pd_proba) * interest_income - (pd_proba * l * EAD)
#     if profit <= 0:
#         break_even = l
#         break
# 
# if break_even:
#     st.info(f"Break-even LGD ≈ {break_even:.2f}")
# else:
#     st.success("Always profitable")
# 
# st.markdown("---")
# st.caption("ML + Business + Decision Engine")

!streamlit run app.py &>/content/logs.txt &

from pyngrok import ngrok

ngrok.set_auth_token("3BG5IwZX2yMrH9uqeJS7MFwySJf_44WyUzg6xbFyrMy3to5yT")

public_url = ngrok.connect(8501)
print(public_url)